
# Configuration file for imp_geo

[data]
data_date=""


[files]
data_folder_path="E:\\MDR source data\\UMLS\\data"
log_folder_path="E:\\MDR source data\\UMLS\\logs"
output_folder_path="E:\\MDR source data\\UMLS\\outputs"


[database]
db_host="localhost"
db_user="postgres"
db_password="WinterIsComing!"
db_port=5433
db_name=""